server:
  tcpServerPort: 9000 # TCP 服务端端口号
  webSocketServerPort: 9001 # WebSocket 服务端端口号
  bossThreadPoolSize: 2 # 主线程池的线程数量
  workerThreadPoolSize: 10 # 子线程池的线程数量
  heartBeatTimeout: 3000 # 心跳检测超时时间
  brokerId: 1001
  loginMode: 1 # 1. 仅允许一台设备在线 2. 允许手机/电脑 + Web 在线 3. 允许手机 + 电脑 + Web 同时在线 4. 允许多台设备同时在线

  redis:
    mode: single # 单机模式：single 哨兵模式：sentinel 集群模式：cluster
    database: 0
    password:
    timeout: 3000 # 超时时间
    poolMinIdle: 8 #最小空闲数
    poolConnTimeout: 3000 # 连接超时时间(毫秒)
    poolSize: 10 # 连接池大小
    single: #redis单机配置
      address: 127.0.0.1:6379

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtualHost: /
    username: 670232228
    password: shinobu

  zookeeper:
    address: 127.0.0.1:2181
    connectTimeout: 5000